CREATE TABLE Accounts
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerId INT NOT NULL FOREIGN KEY REFERENCES Customer(Id),
    AccountNumber NVARCHAR(20) UNIQUE NOT NULL,
    Balance DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    IsActive BIT NOT NULL DEFAULT 1
);
